### ISSUE TITLE
ondiskagg doesn't handle integer types

### ISSUE THREAD

**Issue by bdowling** [alpacahq/marketstore#101]
I attempted to load some OHLCV data where the volume column was an integer type.  ondiskagg doesn't know how to handle this, which resulted in the following error:

```
created by github.com/alpacahq/marketstore/executor.run
        /go/src/github.com/alpacahq/marketstore/executor/written.go:57 +0x154
E0629 03:09:28.348744       1 accum.go:197] no compatible function
E0629 03:09:28.348910       1 written.go:67] recovering from runtime error: invalid memory address or nil pointer dereference
goroutine 181 [running]:
runtime/debug.Stack(0xc421415658, 0xdde200, 0x1656c10)
```

fwiw, it might be helpful additionally if the 'no compatible function' message included the type.

**Comment by umitanuki** [comment]
int32 for volume, which is used for stocks, should be supported. Do you mean int64 or some other integer types? I have to admit that accum.go is missing some types support and agree we should have graceful error than crash
