### ISSUE TITLE
Unable to replay WALFile.1544424147732049389.walfile\nsnappy: corrupt input

### ISSUE THREAD

**Issue by xmurobi** [alpacahq/marketstore#165]
I had upgrade the code to newest version(v3.2.0) and found I can run the marketstore by cmd 
`marketstore start -c mkd.yml`  anymore.

The output like below:
```
{"level":"info","timestamp":"2018-12-09T23:04:43.671-0800","msg":"Running single threaded"}
{"level":"info","timestamp":"2018-12-09T23:04:43.729-0800","msg":"using mkd.yml for configuration"}
{"level":"info","timestamp":"2018-12-09T23:04:43.729-0800","msg":"Disabling \"enable_last_known\" feature until it is fixed..."}
{"level":"info","timestamp":"2018-12-09T23:04:43.730-0800","msg":"initializing marketstore..."}
{"level":"info","timestamp":"2018-12-09T23:04:43.730-0800","msg":"WAL Setup: initCatalog true, initWALCache true, backgroundSync true, WALBypass false: \n"}
{"level":"info","timestamp":"2018-12-09T23:04:43.730-0800","msg":"Root Directory: data"}
{"level":"info","timestamp":"2018-12-09T23:04:50.059-0800","msg":"My WALFILE: WALFile.1544425488825330509.walfile"}
{"level":"info","timestamp":"2018-12-09T23:04:50.059-0800","msg":"Found a WALFILE: WALFile.1544424147732049389.walfile, entering replay..."}
{"level":"info","timestamp":"2018-12-09T23:04:50.589-0800","msg":"Beginning WAL Replay"}
{"level":"info","timestamp":"2018-12-09T23:04:50.589-0800","msg":"Partial Read"}
{"level":"info","timestamp":"2018-12-09T23:04:50.589-0800","msg":"Entering replay of TGData"}
{"level":"info","timestamp":"2018-12-09T23:04:50.589-0800","msg":"Replaying TGID: 1544424167321434338, data length is: 3038 bytes"}
{"level":"fatal","timestamp":"2018-12-09T23:04:50.758-0800","msg":"Unable to replay WALFile.1544424147732049389.walfile\nsnappy: corrupt input"}
```

Looks the new WAL function break the old WAL. Anyone can help?

**Comment by rocketbitz** [comment]
Hi @xmurobi - are you storing fixed or variable length data?

**Comment by xmurobi** [comment]
Hi @rocketbitz , I store both fixed and variable data. Now I removed old WAL file which cause corruption and restart marketstore looks good. 

But after use `marketstore connect`  to query the variable data then got:
Query range: 2011-01-01 00:00:00 +0000 UTC to <nil>
```
{"level":"error","timestamp":"2018-12-10T07:39:50.335-0800","msg":"Error return from query scanner: snappy: corrupt input"}
snappy: corrupt input
```
But for fixed data, everything looks fine.

**Comment by rocketbitz** [comment]
Yes, that makes sense. In our recent release, we have added variable-length data compression, and it is enabled by default. You can disable it in the config file, or when running `connect` you can pass -c to read an uncompressed data set.

**Comment by xmurobi** [comment]
Ok, try -c in `connect` mode and looks good. Also try `disable_variable_compression :true` in mkst.yml for `start` mode and now worked. 

What's disable_variable_compression  use for? to save the disk? Is that I need to set it true forever for old data which had created before this release?

**Comment by rocketbitz** [comment]
The compression for variable length data shrinks the data size roughly 4x, which is quite helpful when storing lots of tick data. The flag just disables it. We will likely include a conversion tool that can be run on old data in a future release.

**Comment by xmurobi** [comment]
Thanks @rocketbitz , for these details.

**Comment by xmurobi** [comment]
Problem solved.
