### ISSUE TITLE
Can I access marketstore from JavaScript?

### ISSUE THREAD

**Issue by Industrial** [alpacahq/marketstore#180]
Hi. I'm building a charting application. Right now I'm using PostgreSQL but I'd love to replace that part with Marketstore.

I'm not using Python in my stack, and I'm using Node.js to write several services. I'm using GraphQL (which supports "Live Queries" in the form of Subscriptions) to connect the browser and API.

How do I query marketstore for history data and live updates without using python?

**Comment by umitanuki** [comment]
You can take a look at RPC interface but the network protocol is based on message pack. The actual data is encoded binary in little endian but I believe node can handle it very well using Typed Array

**Comment by Industrial** [comment]
Are there any plans for a HTTP API for this service?

Or is there an easy way to wrap the API in a HTTP/REST API with Python, perhaps?

**Comment by briancappello** [comment]
@Industrial It's not too hard to wrap it in Python, for example using Flask:

```python
import pymarketstore as pymkts

from flask import Flask, request


app = Flask(__name__)
marketstore = pymkts.Client()


@app.route('/history/<string:symbol>')
def history(symbol):
    timeframe = request.args.get('timeframe', '1D')
    params = pymkts.Params(symbol, timeframe, 'OHLCV')
    df = marketstore.query(params).first().df()
    return df.to_json(orient='split'), 200, {'Content-Type': 'application/json'}


if __name__ == '__main__':
    app.run(debug=True)
```

**Comment by umitanuki** [comment]
Thanks @briancappello for the direction.
