### ISSUE TITLE
aggregator issue

### ISSUE THREAD

**Issue by pvssvikas** [alpacahq/marketstore#184]
In the below observation for 1Min data starting from 9:25 to 9:30 -- I'm not able to see volume getting added as expected. and it is even the same case with other OHLC values.
can you please help my understanding here

019-01-01 09:25:00+05:30 | 201.10 | 201.30 | 201.25 | 201.15 | 11702.0
                                                 200.90 | 201.20 | 201.15 | 200.95 | 36896.0
                                                 200.90 | 201.45 | 201.00 | 201.40 | 28820.0
                                                 201.25 | 201.75 | 201.30 | 201.70 | 17048.0
                                                 201.60 | 201.70 | 201.70 | 201.65 | 8968.0
                                                 201.25 | 201.65 | 201.65 | 201.45 | 26458.0

2019-01-01 09:25:00+05:30 | 201.10 | 201.75 | 201.00 | 201.65 | 103434.0
                                                    201.25 | 201.65 | 201.35 | 201.50 | 81657.0

**Comment by pvssvikas** [comment]
I could just see a reasoning, in a 5min window volume is getting calculated from 9:15 to 9:20 and is reported against 9:15 row;

it is expected to display at 9:20

**Comment by umitanuki** [comment]
Well, using upper bound or lower bound for the bar labelling is always controversial. MarketStore follows the pandas default behavior which is left (lower) bound labeling.
