### ISSUE TITLE
Keep data on restart

### ISSUE THREAD

**Issue by Industrial** [alpacahq/marketstore#189]
Hi. I am using Marketstore with Docker so I am restarting the service a lot. Right now, when the server restarts it imports from the start again.

If there's a cache directory, why isn't it used when it restarts? Am I doing something wrong?

**Comment by umitanuki** [comment]
Which plugin are you talking about?

**Comment by Industrial** [comment]
Never mind. It's my fault :) It's neatly backed up on disk.Sorry,
