### ISSUE TITLE
Questions and Thoughts about TimeBucketKey

### ISSUE THREAD

**Issue by briancappello** [alpacahq/marketstore#194]
Hi,

I've been trying to understand the mechanics of the TimeBucketKey concept how that overlaps/relates to using the custom SQL. Was curious about the intended capabilities for it going forward.

~~If I'm understanding the code correctly, it appears to me that the category keys of the time buckets are tied to the directory structure MarketStore uses on-disk. By extension, it seems to assume there are exactly 3 category keys? Perhaps I'm just misreading.~~

I raise this, because such limitations would appear to complicate adding support for multiple data vendors for the same symbol/timeframe? (eg https://github.com/alpacahq/marketstore/issues/111)

One thought I had to get around this would be to put a database "in front", so for example, if I request the `IEX:TSLA` symbol, then it does a lookup to determine the unique key used on-disk, and the directory structure could remain 3-levels deep without breaking existing stores.

(I'm using `:` which seems to me like the most logic choice, although I realize it's currently taken as a delimeter. I'm not sure if there's any flexibility in changing the existing spec.)

The second question revolves around supporting multiple attribute groups for the same query. Just thinking out loud here, but for example, if I wanted to request `TSLA/1D/OHLCV,MACD(12,26,9)` and have it come back as a single dataframe, is that a desired feature for the future? [the TA could be done on-demand or read from disk]. Something like this could also be done on the client (python) side, if that seems more appropriate.

Would love to hear your guys thoughts! Thanks

**Comment by briancappello** [comment]
I spent some time digging into the source over the weekend, and as far as I can tell, it seems like the backend code around TimeBucketKey does indeed support category keys with more than 3 parts. 

*However*, it also would appear that currently, once you initialize the store with (any) category key, that's that. For example, if I first store some data using the default `Symbol/Timeframe/AttributeGroup`, and I later try to store something using `Vendor/Symbol/Timeframe/AttributeGroup`, it will blow up.

I *think* it should be possible to introduce the concept of having multiple Catalogs on `executor.InstanceMetadata`. Haven't looked into how plugins interact with that, though I suspect they would need to be configured to use a specific catalog / category key.

I'm starting to lean towards this being the "right" way to do this, but again, interested in your feedback :)

**Comment by Notargets** [comment]
I *think* the biggest complication of adding support for more than three levels in metadata is actually in the API - it seems awkward to have to specify the instance key and backing metadata category key as it gets large. It's no accident that this looks like a directory/file structure - it's meant to be a direct map of the underlying filesystem and so can support arbitrary depth as much as the filesystem allows.

The only reason things "blow up" when you're trying to expand the metadata use beyond three levels is that no-one has worked on this yet and so there's likely a lot of broken code in that path - and specifically, the external API is not "ready" for more than three levels.

I'm in favor of using the full keyspace of the catalog if that's useful - I don't see a downside to it, and that's what was intended from the beginning...

**Comment by Notargets** [comment]
Another consideration - we're in the beginning planning stages of scale-out mods for performance and HA - it might be very helpful to use another category level to represent cluster member identity - a catalog split using some form of consistent hashing: https://en.wikipedia.org/wiki/Consistent_hashing

So - lighting up the multi-level functionality buried in the existing catalog seems like a good idea to pursue...

**Comment by briancappello** [comment]
Thanks @Notargets, I really appreciate your insights :)

I finally had a chance last night to start down this rabbit hole a bit, and while I must admit HA is sadly not an area I have much of any experience with, it is something that I'm very interested in learning more about and gainig more experience with.

With that preface out of the way, so far I think I've wrapped my head around consistent hashing (at least conceptually), but it also raised some questions I was hoping you might be able to drop some more hints about.

The wiki article led me to [ketama](https://github.com/RJ/ketama), which after a bit of mucking around I was able to get built and installed, however, the Python bindings are 2.x only and don't appear to wrap the entirety of the C library. Next I tried [uhashring](https://github.com/ultrabug/uhashring), and I had better luck there.

High level, and only considering read-requests and ignoring caching, the picture that's forming in my mind is something like:

[users/clients from the internet] -> request -> [hashring "router"] -> proxied request -> [one of many marketstore instances handles the request]

My understanding here, which might not be right, is that each marketstore instance needs to have access to the entire dataset. That way if one of those boxes goes down for whatever reason, the request can get sent to the next box "on the ring."

Assuming that's more or less accurate, the questions it raises for me arise around writing data / keeping all the stores "in sync". It seems to me like you'd only want a single connection to each of the data provider(s), and that incoming data would then need to fan out to all of the marketstore instances handling client requests.

There's also the question of client-writes. From playing around with `uhashring`, my understanding is that each client has some sort of unique ID (`uuid.uuid4()` seemed to work well) and when that client makes a request, it always ends up pointing to the same marketstore instance (assuming it hasn't gone down). But if it did go down, that data would have needed to propogate to all the other instances so that from the client's perspective, everything appears fine.

Or maybe I'm way off base with all that? I'm hopeful to play around with this some more over the weekend, and I've been wanting to try out Kubernetes too, so this seems like maybe a good opportunity.

---

On the topic of performance, I have maybe a bit more familiarity (at least for *some* parts of the infrastructure). From the docs it sounds to me like marketstore is primarily disk-IO limited? (I think there was mention of being able to saturate a PCIe SSD). The "obvious" thought that occured to me, because of the way the catalog uses directories, would be to just mount separate partitions (living on different physical block devices) under the catalog root dir.

Where I'm less clear is that from this perspective, it almost seems like the category key is "backwards" - if for example I wanted the highest-frequency data going to one SSD, and then all of the other incoming data going to another, and then all of the aggregator writes going to a third... it's not obvious to me how to make that happen.

I wasn't explicit about it before, but that thought also ties into the idea of having multiple catalogs, mounted on different drives. I guess the "brute force" approach here is just to spin up multiple marketstore instances on the same box, each configured with their own (different/key-space-partitioned) `mkts.yml`, and do some kind of routing based on the incoming timebucket keys?

Anyways. At the moment the "barrier to entry" is, I think, lower on the HA side for me (compared to trying to write/refactor Go code), so I think that's the direction I'm going to explore more. But if you got this far (thanks!) a yay/nay vote would be helpful :-D

**Comment by briancappello** [comment]
OK, pretty sure I was making this way more complicated than it needs to be. Here's what I'm currently thinking (see docstring for description):

```python
from collections import defaultdict
from uhashring import HashRing

from typing import *

SymbolBucket = NewType('SymbolBucket', str)  # the name of a symbol bucket
Symbol = NewType('Symbol', str)
Node = NewType('Node', str)                  # the name of a node (IP address or FQDN)
NodeConfKey = NewType('NodeConfKey', str)    # any of NODE_CONF_KEYS
NodeConf = Dict[NodeConfKey, Any]

NODE_CONF_KEYS = {'nodename', 'hostname', 'port', 'weight', 'vnodes', 'instance'}


class RingRouter:
    """
    publicDefaultCategoryKey = 'Symbol/Timeframe/AttributeGroup'
    internalDefaultCategoryKey = 'SymbolBucket/Symbol/Timeframe/AttributeGroup'

    a "symbol bucket" is a named list of symbols
    - it should be a relatively small list, normalized by trading volume

    marketstore instances (nodes) get configured with a list of "symbol bucket" names
    - they pull the actual list of symbols from centralized DB instance
    - each node can support an arbitrary number of symbol buckets depending on its available resources
    - symbol buckets can (should) be duplicated over multiple stores

    This router has a `HashRing` instance for each symbol bucket
    - the client requests a standard `tbk`, same as before
    - we "intercept" the request, use `tbk.symbol` to lookup which symbol bucket has
        the requested data, and then use that symbol bucket's `HashRing` to get
        which specific node the request should be forwarded to.
    """

    def __init__(self,
                 symbol_buckets: Dict[SymbolBucket, List[Symbol]],
                 nodes: Dict[Node, NodeConf],
                 ):
        self._rings: Dict[SymbolBucket, HashRing] = defaultdict(HashRing)
        self._buckets_by_symbol: Dict[Symbol, SymbolBucket] = {
            symbol: symbol_bucket
            for symbol_bucket, symbols in symbol_buckets.items()
            for symbol in symbols
        }
        self._symbol_buckets_by_node = {}
        for node, node_conf in nodes.items():
            self.add_node(node, **node_conf)

    def add_symbol_bucket(self,
                          symbol_bucket: SymbolBucket,
                          symbols: List[Symbol],
                          ) -> None:
        for symbol in symbols:
            self._buckets_by_symbol[symbol] = symbol_bucket

    def add_symbol_to_bucket(self,
                             symbol: Symbol,
                             symbol_bucket: SymbolBucket,
                             ) -> None:
        self._buckets_by_symbol[symbol] = symbol_bucket

    def get_symbol_bucket(self, symbol):
        return self._buckets_by_symbol[symbol]

    def get_node(self,
                 symbol: Symbol,
                 client_id: Union[str, int],
                 ) -> NodeConf:
        symbol_bucket = self._buckets_by_symbol[symbol]
        return self._rings[symbol_bucket].get(client_id)

    def add_node(self,
                 node: Node,
                 symbol_buckets: List[SymbolBucket],
                 **kwargs,
                 ) -> None:
        self._symbol_buckets_by_node[node] = symbol_buckets
        for symbol_bucket in symbol_buckets:
            self._add_bucket_node(symbol_bucket, node,
                                  node_conf=dict(nodename=node, **kwargs))

    def remove_node(self, node: Node) -> None:
        node_symbol_buckets = self._symbol_buckets_by_node.pop(node)
        for symbol_bucket in node_symbol_buckets:
            self._rings[symbol_bucket].remove_node(node)

    def _add_bucket_node(self,
                         symbol_bucket: SymbolBucket,
                         node: Node,
                         node_conf: NodeConf,
                         ) -> None:
        filtered_conf = {k: v for k, v in node_conf.items()
                         if k in NODE_CONF_KEYS and v is not None}
        self._rings[symbol_bucket].add_node(node, filtered_conf)
```

And some basic tests:

```python
import itertools
import pytest

from pymarketstore.ring_router import NODE_CONF_KEYS, RingRouter


# a symbol can only belong to one bucket
BUCKETS = dict(B1=['A', 'AA', 'AMD'],
               B2=['B', 'BB', 'BAC'],
               B3=['C', 'CC', 'CAT'],
               B4=['D', 'DG', 'DDD'],
               )
BUCKET_NAMES = set(BUCKETS.keys())
SYMBOLS = set(itertools.chain.from_iterable(BUCKETS.values()))

# a node can have one or many symbol buckets
NODES = {'1.1.1.1': dict(hostname=None, port=None,
                         weight=1, vnodes=160,
                         symbol_buckets=['B1', 'B2']),
         '2.2.2.2': dict(hostname=None, port=None,
                         weight=1, vnodes=160,
                         symbol_buckets=['B3', 'B4']),
         '3.3.3.3': dict(hostname=None, port=None,
                         weight=1, vnodes=160,
                         symbol_buckets=['B1']),
         '4.4.4.4': dict(hostname=None, port=None,
                         weight=1, vnodes=160,
                         symbol_buckets=['B2']),
         '5.5.5.5': dict(hostname=None, port=None,
                         weight=1, vnodes=160,
                         symbol_buckets=['B3']),
         '6.6.6.6': dict(hostname=None, port=None,
                         weight=1, vnodes=160,
                         symbol_buckets=['B4']),
         '7.7.7.7': dict(hostname=None, port=None,
                         weight=1, vnodes=160,
                         symbol_buckets=['B1', 'B2', 'B3', 'B4']),
         '8.8.8.8': dict(hostname=None, port=None,
                         weight=1, vnodes=160,
                         symbol_buckets=['B3', 'B4']),    RingRouter
         }
BUCKET_NODES = {bucket_name: set(node_name for node_name, conf in NODES.items()
                                 if bucket_name in conf['symbol_buckets'])
                for bucket_name in BUCKET_NAMES}


@pytest.fixture()
def router():
    return RingRouter(BUCKETS, NODES)


class TestRingRouter:
    def test_init(self):
        router = RingRouter(BUCKETS, NODES)
        assert set(router._buckets_by_symbol.keys()) == SYMBOLS
        assert set(router._buckets_by_symbol.values()) == BUCKET_NAMES

        assert set(router._rings.keys()) == BUCKET_NAMES
        for bucket in BUCKET_NAMES:
            assert set(router._rings[bucket].get_nodes()) == BUCKET_NODES[bucket]

    @pytest.mark.parametrize('symbol', ['A', 'B', 'C', 'D'])
    def test_get_node(self, router: RingRouter, symbol):
        nodes = set()
        expected_nodes = BUCKET_NODES[router.get_symbol_bucket(symbol)]
        for i in range(0, 100):
            node_conf = router.get_node(symbol=symbol, client_id=f'client{i}')
            assert set(node_conf.keys()) == NODE_CONF_KEYS
            assert node_conf['nodename'] in expected_nodes
            nodes.add(node_conf['nodename'])

        assert nodes == expected_nodes

    def test_add_node(self, router: RingRouter):
        node = '9.9.9.9'
        bucket = 'B1'
        router.add_node(node, symbol_buckets=[bucket])
        assert node in router._rings[bucket].get_nodes()
        assert router._symbol_buckets_by_node[node] == ['B1']
        assert router._rings[bucket].get(node) == dict(
            nodename=node,
            hostname=node,
            port=None,
            instance=None,
            vnodes=160,
            weight=1,
        )

    def test_remove_node(self, router: RingRouter):
        node = '8.8.8.8'
        buckets = NODES[node]['symbol_buckets']
        router.remove_node(node)
        for bucket in buckets:
            assert node not in router._rings[bucket].get_nodes()
```

Limitations / stuff that hasn't received much thought:

* I don't think this allows for (easily) "rebalancing" symbol buckets
    - I'm basically assuming symbol buckets start small, and symbols are never removed (which I think is OK, given survivorship bias)
* What happens when a symbol gets renamed on the exchange? (I think we can just rename everywhere on our end and it should be fine?)
* My earlier questions about syncing writes across marketstore instances remain
* Need to give thought to making sure this is an optional "add-on" (ie that a single marketstore can be run as it exists now, without any HA stuffs)
