### ISSUE TITLE
[Proposal] Millisec support / 8byte Interval Ticks for Variable-Length Data 

### ISSUE THREAD

**Issue by dakimura** [alpacahq/marketstore#197]
My proposal is to modify marketstore to avoid any sub-second errors by one of the followings:
- change the size of `IntervalTicks` from 4byte to 8byte.
- truncate last 6 digits of `Nanoseconds` and add`Millisecs` support.

I'm wondering if `nanoseconds` resolution would be too much  and `milliseconds` is enough for 
real-life market data. Currently, marketstore is using 4byte `Interval Ticks` to handle multiple ticks in one interval. However, 4byte is not enough resolution to distinguish Nanosecond-level data, which sometimes results in confusion.

ex)
write 4 records with nanosec=0, 6, 12,18 ....
```
import pymarketstore as pymkts
import pandas as pd
import numpy as np

cli = pymkts.Client()

nanosec = 0
data = np.array([(pd.Timestamp('2019-01-01 00:00:00').value / 10**9, 1, 2, nanosec)],dtype=[('Epoch', 'i8'), ('Bid', 'f4'), ('Ask', 'f4'), ('Nanoseconds', 'i4')])
cli.write(data, "TEST/1Min/TICK", isvariablelength=True)

nanosec = 6
data = np.array([(pd.Timestamp('2019-01-01 00:00:00').value / 10**9, 1, 2, nanosec)],dtype=[('Epoch', 'i8'), ('Bid', 'f4'), ('Ask', 'f4'), ('Nanoseconds', 'i4')])
cli.write(data, "TEST/1Min/TICK", isvariablelength=True)

nanosec = 12
data = np.array([(pd.Timestamp('2019-01-01 00:00:00').value / 10**9, 1, 2, nanosec)],dtype=[('Epoch', 'i8'), ('Bid', 'f4'), ('Ask', 'f4'), ('Nanoseconds', 'i4')])
cli.write(data, "TEST/1Min/TICK", isvariablelength=True)

nanosec = 18
data = np.array([(pd.Timestamp('2019-01-01 00:00:00').value / 10**9, 1, 2, nanosec)],dtype=[('Epoch', 'i8'), ('Bid', 'f4'), ('Ask', 'f4'), ('Nanoseconds', 'i4')])
cli.write(data, "TEST/1Min/TICK", isvariablelength=True)
```

nanosec = 0, 0, 0, 13 !!?? what happened!!??
```
» \show TEST/1Min/TICK 1970-01-01
=============================  ==========  ==========  ==========  
                        Epoch  Bid         Ask         Nanoseconds  
=============================  ==========  ==========  ==========  
2019-01-01 00:00:00 +0000 UTC    1           2           0           
2019-01-01 00:00:00 +0000 UTC    1           2           0           
2019-01-01 00:00:00 +0000 UTC    1           2           0           
2019-01-01 00:00:00 +0000 UTC    1           2           13          
=============================  ==========  ==========  ==========
```

In order to avoid this situation, I'm thinking 2 solutions.

1) increase the size of `IntervalTicks` to 8byte
By using 4byte (= `2**32` )Interval Ticks,  the resolution is ...
(Timeframe)1Min :   `60*10**9 / 2**32 = 13.969838619232178 (Nanosec / IntervalTick)`
By using 8byte (= `2**64` )Interval Ticks, the resolution is ...
(Timeframe)1Min :   `60*10**9 / 2**64 = 5.421010862427522e-11 (Nanosec/ IntervalTick) ≒0`
We can handle nanosec level variable-length data.
However, we need to change the spec of data format.

2) add Millisec support
If `Millisec` columns are sent to the marketstore server, we multiply 10**6 to them and treat them as Nanosecond columns.
```
data = np.array([(pd.Timestamp('2019-01-01 00:00:00').value / 10**9, 1, 2, 123)],dtype=[('Epoch', 'i8'), ('Bid', 'f4'), ('Ask', 'f4'), ('Milliseconds', 'i4')])
cli.write(data, "TEST/1Min/TICK", isvariablelength=True)
```
4 byte resolution is enough to distinguish milliseconds-level data, so we don't need to change the spec of format.

Could you tell me which solution fits to the roadmap of marketstore?
I think that `Adding `1Sec` timeframe support and use the 4byte space for Nanoseconds` is also one alternative because both `Nanoseconds` and `IntervalTicks` are 4 bytes....
Of course I'm happy to implement one of these solutions by myself.

Thank you!

**Comment by umitanuki** [comment]
I'd have to read it through and understand the issue, but nanoseconds is important for SIP data.

**Comment by Notargets** [comment]
Hi Daito!

Thanks for your good documentation of this - it is an accurate reflection of the situation - we have resolution of around +/- 15ns for variable length buckets in the 1Min timeframe. If we were to use a 1Sec timeframe, the resolution would be full nanosecond at +/- 0.25 ns.

What complicates your proposal is that the interval resolution is dynamic, depending on the timeframe of the bucket, which creates the question: what should we truncate the resolution to?

What would be great is if we can truncate the res to the nearest 1/1000th of a second - so for 1Min buckets we would truncate to microseconds and then for 1Sec buckets we'd truncate to nanos and so on.

If we were to go down the other path and use 64 bits to store the timestamps, we wouldn't need the fancy interval arithmetic and things would be simpler, but we'd be adding four more bytes per tick - is that worth it? I feel like my answer is "no" in that we're envisioning storing all of the SIP level 1 and 2 data and trying to fit it into the smallest space possible - so adding a significant amount of storage space should come with some benefits...

**Comment by dakimura** [comment]
Hi Luke san,

Thank you for your clear explanation! I understand the situation and the roadmap of marketstore.

> If we were to use a 1Sec timeframe, the resolution would be full nanosecond at +/- 0.25 ns.
Yes, and it seems that it's almost supported.
https://github.com/alpacahq/marketstore/issues/108

I will look into the current implementation of marketstore and see how I can work to resolve this issue.

Thank you!
Daito
