### ISSUE TITLE
[Help Wantend] Use case fit

### ISSUE THREAD

**Issue by gcaracuel** [alpacahq/marketstore#213]
Sorry to post this as an issue but need some help to clarify if this tool could solve my use case.

- Does markestore allow to store also some calculated data? For example, I would like to store some indicators calculations so then I could easily graph them directly from marketstore extract.

- Are there any example on how to integrate stocks ticks / intraday data? hour timeframe is more than fine. If someone can point me to an example that would be nice. Is there a chat group to talk about this kind of questions regarding marketstore?

- Does marketstore consolidate the aggregated to save space disk on long term runing instances?

Thanks in advance,

**Comment by bdowling** [comment]
You can store any numeric data you like, currently there are no plugins that do technical analysis, but you can do your own and feed the data back in.

In the contrib/ folder are a number of plugins that can fetch data and keep it updated.  IEX, Polygon in particular.

Yes it handles data aggregation, but currently does not remove the finite data, you'd need to prune that yourself if you no longer need it.

You can find out more about our communities from our homepage and docs.
https://alpaca.markets
https://forum.alpaca.markets/
