### ISSUE TITLE
Update the Dockerfile to make it easier to upgrade between versions

### ISSUE THREAD

**Issue by rymdluo** [alpacahq/marketstore#229]
# The Issue

The current Dockerfile automatically creates a default config file at `/etc/mkts.yml` and starts it. The only way to use the preloaded docker image with custom config file is by copying your own and starting it again. This makes upgrading inefficient using the docker images since it requires manual replacement after each upgrade.

# The Workaround

Currently, I load a carbon copy of marketstore with very small changes to the Dockerfile to copy my config file and run that config file instead of the default. There is also the suggestion provided in the README, however they all require manual intervention.

# Proposed Solution
It would improve quality of life/work if the start command could check if a `mkts.yml` file is found in the persistent `/data` directory and load it if true. 

# The Benefits
This allows users to use the latest docker images without manual intervention. The user's config file is stored in a persistent directory means their config will persist throughout versions and upgrades, and only needs to be uploaded once (barring any modifications).

**Comment by bdowling** [comment]
You can pass in your own command line to override the default, and point to a config in a mounted volume for example.

`-v /data:/data alpacamarkets/marketstore:latest  start -c /data/cfg/mkts.yml`
