### ISSUE TITLE
Is it possible to remove / delete data?

### ISSUE THREAD

**Issue by jaredmcqueen** [alpacahq/marketstore#264]
I searched these issues, documentation, and even the source code for the python client.

Is it currently possible to remove data from marketstore via the api?

**Comment by zjhmale** [comment]
Hi, through the source code, there is a `trim` command to do this job.

**Comment by goodboy** [comment]
@jaredmcqueen yes, you use the [`pymarketstore.Client.destroy()` method](https://github.com/alpacahq/pymarketstore/blob/master/pymarketstore/client.py#L126). I'm not sure if you can remove individual rows from a single time bucket table or not.

**Comment by goodboy** [comment]
@zjhmale I assume you're referring to [this function?](https://github.com/alpacahq/marketstore/blob/4811cc6a14a917e97261ce19b223d9b15325037e/cmd/connect/session/trim.go#L14).
