### ISSUE TITLE
How to backup the marketstore database?

### ISSUE THREAD

**Issue by nyxynyx** [alpacahq/marketstore#330]
What is the recommended way to backup marketstore data? 

I'll like to testdrive marketstore for potential use in production and performing backups and restores are pretty crucial requirements for my use case.

Are incremental backups possible?

**Comment by goodboy** [comment]
There's a tip in my docs PR (#321) but, it seems data is stored in binary format to the local filesystem to a directory of your choosing. The file layout is detailed in the [design doc](https://github.com/alpacahq/marketstore/blob/master/docs/design/file_format_design.txt). As far as I understand the format is already tuned to save space using relative counts from a timestamp. 

So really you can use any system that backs up from the filesystem.
I'm personally a fan of [borg](https://github.com/borgbackup/borg).
The alpaca peeps likely have their own methodology though.

**Comment by tibkiss** [comment]
marketstore uses sparse files, so it is helpful to enable that in your backup.

taking backups can be as simple as tar-ing or rsync-ing the data dir if you are on VMs,
or taking a snapshot of the underlying PV in case of Kubernetes.
