### ISSUE TITLE
Unable to compile plugins

### ISSUE THREAD

**Issue by gducharme** [alpacahq/marketstore#61]
I'm having a few problems compiling the plugins.

1) Easy to solve, but the compiler needed to be set to c99. ```export CC=c99``` fixed that.
2) A little more obscure, a regression that prevents ondiskagg from compiling. This is a bug from [go](https://groups.google.com/forum/#!topic/Golang-Nuts/69SoQWwYWtk) introduced last December. This can be worked around by using go 1.9.1. This seems to come from a c99 vs a gnu99 issue.
3)  Still having an issue with 
```
gcc_linux_amd64.c: In function ‘_cgo_sys_thread_start’:
gcc_linux_amd64.c:62:2: error: unknown type name ‘sigset_t’
```
Not sure what this one is.

The system is on Redhat x86_64 GNU/Linux. If there's a recommended system architecture, please let me know. I'll be using the Docker image in the mean time.

**Comment by umitanuki** [comment]
3) is very weird.  Sounds like it's a go toolchain problem but cannot find much on the web.  Only thing I could find is related a build on Windows https://stackoverflow.com/questions/49100108/get-error-when-try-to-build-go-code-for-linux-on-windows-10 (2 months ago, not sure what version of go)

We usually build it on alpine but ubuntu should also build. Go's plugin is relatively new so there might be issues on some platforms.
