### ISSUE TITLE
binance feeder broken for specific symbols

### ISSUE THREAD

**Issue by Darkbladecr** [alpacahq/marketstore#92]
```
I0624 23:28:22.273633   21515 binancefeeder.go:198] Requesting ETHBTC 2018-06-20 00:00:00 +0000 UTC - 2018-06-20 05:00:00 +0000 UTC
E0624 23:28:22.494356   21515 binancefeeder.go:203] Response error: <APIError> code=-1121, msg=Invalid symbol.
```
I keep receiving the API error code =-1121
when trying [any of the symbol pairs](https://api.binance.com/api/v1/exchangeInfo) available from the API

**Comment by ethanchewy** [comment]
For now, it only support USD prices. 

You can change it manually by removing "USDT" https://github.com/alpacahq/marketstore/blob/master/contrib/binancefeeder/binancefeeder.go#L200

and changing your mkts.yml file to:
symbols:
        - ETHBTC

**Comment by Darkbladecr** [comment]
hmm how come you go with this hardcode? Wouldn't it make sense to let the user decide the pairs they want to monitor?

**Comment by ethanchewy** [comment]
It's not a priority at the moment. We'll change it soon.

**Comment by rocketbitz** [comment]
He was just following what gdaxfeeder does. I will close this and open separate issues to support non-USD pairs in both gdaxfeeder and binancefeeder plugins.
